#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /opt/bin/mjpg_streamer \
        -i "input_uvc.so -d /dev/video0 -r 1280x720 -f 30" \
        -o "output_http.so -p 8080 -w /www/webcam"
    procd_set_param respawn
    procd_close_instance
}
